### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by remiznik** [remiznik/Curious#12]
- [ ] найти удобный профайлер
- [ ] добавить его как third party
- [ ] добавить документацию с описанием как работать с профайлкром
- [ ] добавить аллокатор памяти и счётчики памяти
- [ ] выводить фпс и основные метрики на экран (возможно заюзать ImGui)
