### ISSUE TITLE
Create branch for Milestone "Simple Scene"

### ISSUE THREAD

**Issue by remiznik** [remiznik/Curious#24]
- [x] вмерижть Render в Master
- [x] удалить старые бранчи
- [x] срезать бранч для Milestone

**Comment by remiznik** [comment]
318e8151b1b638bf10b4a04d2c32c3758e176999
