### ISSUE TITLE
Refactoring VM

### ISSUE THREAD

**Issue by remiznik** [remiznik/Curious#4]
Rewrite Virtual machine from C to C++
- [ ] [Rewrite Value](https://app.gitkraken.com/glo/card/02fff42024ec4521a8a38c60be9ed450)
- [ ] [Rewrite c string to std string ](https://app.gitkraken.com/glo/card/2bb9efacb7ae439ca82a7eae8c1d0391)
- [ ] Rewrite hastabel 
- [ ] Separate Hash Table and Global String container
